import { describe, expect, it } from "vitest";
import {
  buildQualificationFallback,
  buildRelationshipIntelligenceFallback,
  buildQuoteDraftFallback,
  buildReplyDraftFallback,
  type WorkflowFallbackContext,
} from "../fallbacks";

const baseContext = {
  lead: {
    id: "lead-1",
    company_name: "Acme CRM",
    contact_name: "Jamie Chan",
    contact_email: "jamie@example.com",
    enquiry_text: "We need an urgent CRM launch this month with a clear HKD budget.",
    qualification_data: null,
  },
  pricing_templates: [
    {
      id: "price-1",
      service: "CRM Launch Sprint",
      description: "Implementation sprint for CRM activation",
      category: "CRM",
      unit_price: 42000,
      currency: "HKD",
    },
    {
      id: "price-2",
      service: "Growth Retainer",
      description: "Monthly growth support",
      category: "campaign",
      unit_price: 58000,
      currency: "HKD",
    },
    {
      id: "price-3",
      service: "Analytics Setup",
      description: "Dashboard implementation",
      category: "data",
      unit_price: 26000,
      currency: "HKD",
    },
  ],
} satisfies WorkflowFallbackContext;

describe("workflow fallback builders", () => {
  it("builds deterministic qualification score and service interest", () => {
    const payload = buildQualificationFallback({
      context: baseContext,
      agentRunId: "run-abcdef123456",
    });

    expect(payload.lead_score).toBe(80);
    expect(payload.qualification_data).toMatchObject({
      urgency_score: 8,
      fit_score: 8,
      qualification_score: 80,
      service_interest: ["CRM Launch Sprint"],
      next_action: "Schedule discovery call",
      human_review_required: true,
    });
    expect(payload.output_summary).toBe("Fallback qualification scored Acme CRM at 80.");
    expect(payload.model_used).toBe("deterministic-fallback");
  });

  it("builds a reply with the contact first name and review risk note", () => {
    const payload = buildReplyDraftFallback({
      context: baseContext,
      agentRunId: "run-abcdef123456",
    });

    expect(payload.draft_message).toContain("Hi Jamie,");
    expect(payload.draft_message).toContain("CRM Launch Sprint");
    expect(payload.risk_notes).toEqual([
      "Generated by deterministic fallback; review tone and commercial claims before sending.",
    ]);
  });

  it("builds deterministic quote number and valid-until date when now is injected", () => {
    const payload = buildQuoteDraftFallback({
      context: baseContext,
      agentRunId: "run-abcdef123456",
      now: new Date("2026-05-24T12:00:00.000Z"),
    });

    expect(payload.quote.number).toBe("FIM-RUN-ABCD");
    expect(payload.quote.valid_until).toBe("2026-06-07");
    expect(payload.quote.total_value).toBe(42000);
    expect(payload.quote.line_items).toHaveLength(1);
  });

  it("still creates one line item when no pricing template matches", () => {
    const context = {
      ...baseContext,
      lead: {
        ...baseContext.lead,
        company_name: "Unrelated Co",
        enquiry_text: "We need an executive briefing.",
      },
    } satisfies WorkflowFallbackContext;

    const payload = buildQuoteDraftFallback({
      context,
      agentRunId: "run-abcdef123456",
      now: new Date("2026-05-24T12:00:00.000Z"),
    });

    expect(payload.quote.line_items).toEqual([
      {
        id: "line-1",
        service: "CRM Launch Sprint",
        description: "Implementation sprint for CRM activation",
        qty: 1,
        unit_price: 42000,
      },
    ]);
    expect(payload.quote.currency).toBe("HKD");
    expect(payload.quote.total_value).toBe(42000);
  });

  it("builds deterministic relationship intelligence output with explainable signals", () => {
    const payload = buildRelationshipIntelligenceFallback({
      account: {
        id: "account-1",
        name: "Acme CRM",
        lifecycle_stage: "active_client",
        account_owner: null,
      },
      contacts: [
        {
          id: "contact-1",
          relationship_role: "buyer",
          influence_level: "high",
          sentiment: "negative",
          last_contacted_at: "2026-04-01T00:00:00.000Z",
        },
      ],
      engagements: [
        {
          id: "engagement-1",
          product_id: "product-1",
          status: "active",
          renewal_risk: "high",
          last_touch_at: "2026-05-01T00:00:00.000Z",
        },
      ],
      quotes: [],
      campaignMembers: [
        {
          id: "member-1",
          campaign_id: "campaign-1",
          attendee_status: "attended",
          follow_up_status: "not_started",
          created_at: "2026-05-19T00:00:00.000Z",
        },
      ],
      products: [
        { id: "product-1", name: "CRM Launch Sprint", active: true },
        { id: "product-2", name: "Growth Retainer", active: true },
      ],
      agentRunId: "run-rel-1",
      now: new Date("2026-05-24T12:00:00.000Z"),
    });

    expect(payload.account_id).toBe("account-1");
    expect(payload.agent_run_id).toBe("run-rel-1");
    expect(payload.output_summary).toBe(
      "Fallback relationship scan found 8 signals for Acme CRM.",
    );
    expect(payload.next_action).toBe(
      "Identify and add the decision maker before the next commercial step.",
    );
    expect(payload.confidence_score).toBe(0.62);
    expect(payload.model_used).toBe("deterministic-fallback");
    expect(payload.signals).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          signal_type: "missing_decision_maker",
          severity: "high",
          reason: "Acme CRM has no mapped decision maker.",
        }),
        expect.objectContaining({
          signal_type: "missing_champion",
          severity: "medium",
        }),
        expect.objectContaining({
          signal_type: "stale_touchpoint",
          title: "Relationship touchpoint is stale",
        }),
        expect.objectContaining({
          signal_type: "post_event_follow_up_due",
          dedupe_key: "campaign-member-member-1",
        }),
        expect.objectContaining({
          signal_type: "high_risk_engagement",
          dedupe_key: "high-risk-engagement-engagement-1",
        }),
        expect.objectContaining({
          signal_type: "negative_sentiment",
          dedupe_key: "negative-sentiment-contact-1",
        }),
        expect.objectContaining({
          signal_type: "unowned_account",
          dedupe_key: "unowned-account",
        }),
        expect.objectContaining({
          signal_type: "cross_sell_opportunity",
          dedupe_key: "cross-sell-product-2",
        }),
      ]),
    );
  });
});
