import { describe, expect, it } from "vitest";
import {
  buildQualificationFallback,
  buildQuoteDraftFallback,
  buildReplyDraftFallback,
  type WorkflowFallbackContext,
} from "../fallbacks";

const baseContext = {
  lead: {
    id: "lead-1",
    company_name: "Acme CRM",
    contact_name: "Jamie Chan",
    contact_email: "jamie@example.com",
    enquiry_text: "We need an urgent CRM launch this month with a clear HKD budget.",
    qualification_data: null,
  },
  pricing_templates: [
    {
      id: "price-1",
      service: "CRM Launch Sprint",
      description: "Implementation sprint for CRM activation",
      category: "CRM",
      unit_price: 42000,
      currency: "HKD",
    },
    {
      id: "price-2",
      service: "Growth Retainer",
      description: "Monthly growth support",
      category: "campaign",
      unit_price: 58000,
      currency: "HKD",
    },
    {
      id: "price-3",
      service: "Analytics Setup",
      description: "Dashboard implementation",
      category: "data",
      unit_price: 26000,
      currency: "HKD",
    },
  ],
} satisfies WorkflowFallbackContext;

describe("workflow fallback builders", () => {
  it("builds deterministic qualification score and service interest", () => {
    const payload = buildQualificationFallback({
      context: baseContext,
      agentRunId: "run-abcdef123456",
    });

    expect(payload.lead_score).toBe(80);
    expect(payload.qualification_data).toMatchObject({
      urgency_score: 8,
      fit_score: 8,
      qualification_score: 80,
      service_interest: ["CRM Launch Sprint"],
      next_action: "Schedule discovery call",
      human_review_required: true,
    });
    expect(payload.output_summary).toBe("Fallback qualification scored Acme CRM at 80.");
    expect(payload.model_used).toBe("deterministic-fallback");
  });

  it("builds a reply with the contact first name and review risk note", () => {
    const payload = buildReplyDraftFallback({
      context: baseContext,
      agentRunId: "run-abcdef123456",
    });

    expect(payload.draft_message).toContain("Hi Jamie,");
    expect(payload.draft_message).toContain("CRM Launch Sprint");
    expect(payload.risk_notes).toEqual([
      "Generated by deterministic fallback; review tone and commercial claims before sending.",
    ]);
  });

  it("builds deterministic quote number and valid-until date when now is injected", () => {
    const payload = buildQuoteDraftFallback({
      context: baseContext,
      agentRunId: "run-abcdef123456",
      now: new Date("2026-05-24T12:00:00.000Z"),
    });

    expect(payload.quote.number).toBe("FIM-RUN-ABCD");
    expect(payload.quote.valid_until).toBe("2026-06-07");
    expect(payload.quote.total_value).toBe(42000);
    expect(payload.quote.line_items).toHaveLength(1);
  });

  it("still creates one line item when no pricing template matches", () => {
    const context = {
      ...baseContext,
      lead: {
        ...baseContext.lead,
        company_name: "Unrelated Co",
        enquiry_text: "We need an executive briefing.",
      },
    } satisfies WorkflowFallbackContext;

    const payload = buildQuoteDraftFallback({
      context,
      agentRunId: "run-abcdef123456",
      now: new Date("2026-05-24T12:00:00.000Z"),
    });

    expect(payload.quote.line_items).toEqual([
      {
        id: "line-1",
        service: "CRM Launch Sprint",
        description: "Implementation sprint for CRM activation",
        qty: 1,
        unit_price: 42000,
      },
    ]);
    expect(payload.quote.currency).toBe("HKD");
    expect(payload.quote.total_value).toBe(42000);
  });
});
