import type { Lead, PricingTemplate } from "@/lib/types";
import type {
  QualificationWritebackPayload,
  QuoteDraftWritebackPayload,
  ReplyDraftWritebackPayload,
} from "@/lib/workflows/types";

export type WorkflowFallbackContext = {
  lead: Pick<
    Lead,
    "id" | "company_name" | "contact_name" | "contact_email" | "enquiry_text" | "qualification_data"
  >;
  pricing_templates: Array<
    Pick<PricingTemplate, "id" | "service" | "description" | "category" | "unit_price" | "currency">
  >;
};

type WorkflowFallbackInput = {
  context: WorkflowFallbackContext;
  agentRunId: string;
};

type QuoteFallbackInput = WorkflowFallbackInput & {
  now: Date;
};

const DEFAULT_PRICE = 18000;
const DEFAULT_CURRENCY = "HKD";

function textForLead(lead: WorkflowFallbackContext["lead"]) {
  return [lead.company_name, lead.contact_name, lead.contact_email, lead.enquiry_text]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}

function matchingPricingTemplates(context: WorkflowFallbackContext) {
  const text = textForLead(context.lead);
  return context.pricing_templates.filter((template) => {
    const haystack = [template.service, template.category, template.description]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();

    return haystack
      .split(/\s+/)
      .filter((token) => token.length > 3)
      .some((token) => text.includes(token));
  });
}

function pickPricingTemplates(context: WorkflowFallbackContext) {
  const matches = matchingPricingTemplates(context);
  return (matches.length > 0 ? matches : context.pricing_templates).slice(0, 2);
}

function addDays(date: Date, days: number) {
  const next = new Date(date);
  next.setUTCDate(next.getUTCDate() + days);
  return next.toISOString().slice(0, 10);
}

function quoteNumber(agentRunId: string) {
  return `FIM-${agentRunId.slice(0, 8).toUpperCase()}`;
}

export function buildQualificationFallback({
  context,
  agentRunId,
}: WorkflowFallbackInput): QualificationWritebackPayload {
  const text = textForLead(context.lead);
  const selected = pickPricingTemplates(context);
  const urgencyScore = /urgent|asap|launch|deadline|this month|q[1-4]/i.test(text) ? 8 : 6;
  const fitScore = selected.length > 0 ? 8 : 6;
  const score = Math.min(95, Math.round((urgencyScore + fitScore) * 5));

  return {
    lead_id: context.lead.id,
    agent_run_id: agentRunId,
    lead_score: score,
    qualification_data: {
      urgency_score: urgencyScore,
      fit_score: fitScore,
      qualification_score: score,
      service_interest: selected.map((template) => template.service),
      budget_range: /\bhkd\b|\$|budget|retainer|monthly/i.test(text) ? "HKD 50k-200k" : "unknown",
      next_action: score >= 75 ? "Schedule discovery call" : "Request more info",
      reason: "Deterministic staging fallback based on enquiry text and active pricing templates.",
      confidence: 0.64,
      human_review_required: true,
    },
    output_summary: `Fallback qualification scored ${context.lead.company_name} at ${score}.`,
    confidence_score: 0.64,
    model_used: "deterministic-fallback",
  };
}

export function buildReplyDraftFallback({
  context,
  agentRunId,
}: WorkflowFallbackInput): ReplyDraftWritebackPayload {
  const firstName = context.lead.contact_name?.split(/\s+/)[0] ?? "there";
  const selected = pickPricingTemplates(context);
  const services =
    selected.map((template) => template.service).join(", ") || "CRM and growth support";

  return {
    lead_id: context.lead.id,
    agent_run_id: agentRunId,
    draft_message: [
      `Hi ${firstName},`,
      "",
      `Thanks for reaching out to Fimmick about ${services}. We can help map the opportunity, clarify the best-fit scope, and recommend a practical next step for ${context.lead.company_name}.`,
      "",
      "Would you be open to a short discovery call this week so we can confirm goals, timeline, and budget range before we propose the right package?",
      "",
      "Best,",
      "Fimmick ClientOps",
    ].join("\n"),
    context_summary: `Fallback reply drafted for ${context.lead.company_name}.`,
    confidence_score: 0.62,
    risk_notes: [
      "Generated by deterministic fallback; review tone and commercial claims before sending.",
    ],
  };
}

export function buildQuoteDraftFallback({
  context,
  agentRunId,
  now,
}: QuoteFallbackInput): QuoteDraftWritebackPayload {
  const matches = matchingPricingTemplates(context);
  const selected = (matches.length > 0 ? matches : context.pricing_templates).slice(
    0,
    matches.length > 0 ? 2 : 1,
  );
  const lineItems = selected.map((template, index) => ({
    id: `line-${index + 1}`,
    service: template.service,
    description: template.description ?? `${template.service} support package`,
    qty: 1,
    unit_price: Number(template.unit_price ?? DEFAULT_PRICE),
  }));
  const finalLineItems =
    lineItems.length > 0
      ? lineItems
      : [
          {
            id: "line-1",
            service: "ClientOps Discovery Sprint",
            description: "Discovery and recommendation sprint for the lead follow-up opportunity.",
            qty: 1,
            unit_price: DEFAULT_PRICE,
          },
        ];

  return {
    lead_id: context.lead.id,
    agent_run_id: agentRunId,
    quote: {
      number: quoteNumber(agentRunId),
      currency: selected[0]?.currency ?? DEFAULT_CURRENCY,
      total_value: finalLineItems.reduce((sum, item) => sum + item.qty * item.unit_price, 0),
      valid_until: addDays(now, 14),
      line_items: finalLineItems,
    },
    create_send_approval: true,
    context_summary: `Fallback quote drafted for ${context.lead.company_name}.`,
    confidence_score: 0.6,
  };
}
