/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as QuotesIdRouteImport } from './routes/quotes.$id'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as AgentsNameRouteImport } from './routes/agents.$name'
import { Route as ApiWorkflowsQualifyLeadRouteImport } from './routes/api/workflows/qualify-lead'
import { Route as ApiWorkflowsDraftReplyRouteImport } from './routes/api/workflows/draft-reply'
import { Route as ApiWorkflowsDraftQuoteRouteImport } from './routes/api/workflows/draft-quote'
import { Route as ApiWorkflowsContextLeadRouteImport } from './routes/api/workflows/context/lead'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesIdRoute = QuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuotesRoute,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const AgentsNameRoute = AgentsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiWorkflowsQualifyLeadRoute = ApiWorkflowsQualifyLeadRouteImport.update({
  id: '/api/workflows/qualify-lead',
  path: '/api/workflows/qualify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsDraftReplyRoute = ApiWorkflowsDraftReplyRouteImport.update({
  id: '/api/workflows/draft-reply',
  path: '/api/workflows/draft-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsDraftQuoteRoute = ApiWorkflowsDraftQuoteRouteImport.update({
  id: '/api/workflows/draft-quote',
  path: '/api/workflows/draft-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsContextLeadRoute = ApiWorkflowsContextLeadRouteImport.update({
  id: '/api/workflows/context/lead',
  path: '/api/workflows/context/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/agents/$name': typeof AgentsNameRoute
  '/clients/$id': typeof ClientsIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/api/workflows/draft-quote': typeof ApiWorkflowsDraftQuoteRoute
  '/api/workflows/draft-reply': typeof ApiWorkflowsDraftReplyRoute
  '/api/workflows/qualify-lead': typeof ApiWorkflowsQualifyLeadRoute
  '/api/workflows/context/lead': typeof ApiWorkflowsContextLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/agents/$name': typeof AgentsNameRoute
  '/clients/$id': typeof ClientsIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/api/workflows/draft-quote': typeof ApiWorkflowsDraftQuoteRoute
  '/api/workflows/draft-reply': typeof ApiWorkflowsDraftReplyRoute
  '/api/workflows/qualify-lead': typeof ApiWorkflowsQualifyLeadRoute
  '/api/workflows/context/lead': typeof ApiWorkflowsContextLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/agents/$name': typeof AgentsNameRoute
  '/clients/$id': typeof ClientsIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/api/workflows/draft-quote': typeof ApiWorkflowsDraftQuoteRoute
  '/api/workflows/draft-reply': typeof ApiWorkflowsDraftReplyRoute
  '/api/workflows/qualify-lead': typeof ApiWorkflowsQualifyLeadRoute
  '/api/workflows/context/lead': typeof ApiWorkflowsContextLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/agents'
    | '/approvals'
    | '/clients'
    | '/leads'
    | '/login'
    | '/notifications'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/agents/$name'
    | '/clients/$id'
    | '/leads/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/api/workflows/draft-quote'
    | '/api/workflows/draft-reply'
    | '/api/workflows/qualify-lead'
    | '/api/workflows/context/lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/agents'
    | '/approvals'
    | '/clients'
    | '/leads'
    | '/login'
    | '/notifications'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/agents/$name'
    | '/clients/$id'
    | '/leads/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/api/workflows/draft-quote'
    | '/api/workflows/draft-reply'
    | '/api/workflows/qualify-lead'
    | '/api/workflows/context/lead'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/agents'
    | '/approvals'
    | '/clients'
    | '/leads'
    | '/login'
    | '/notifications'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/agents/$name'
    | '/clients/$id'
    | '/leads/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/api/workflows/draft-quote'
    | '/api/workflows/draft-reply'
    | '/api/workflows/qualify-lead'
    | '/api/workflows/context/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  QuotesRoute: typeof QuotesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  ApiWorkflowsDraftQuoteRoute: typeof ApiWorkflowsDraftQuoteRoute
  ApiWorkflowsDraftReplyRoute: typeof ApiWorkflowsDraftReplyRoute
  ApiWorkflowsQualifyLeadRoute: typeof ApiWorkflowsQualifyLeadRoute
  ApiWorkflowsContextLeadRoute: typeof ApiWorkflowsContextLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/agents/$name': {
      id: '/agents/$name'
      path: '/$name'
      fullPath: '/agents/$name'
      preLoaderRoute: typeof AgentsNameRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/api/workflows/qualify-lead': {
      id: '/api/workflows/qualify-lead'
      path: '/api/workflows/qualify-lead'
      fullPath: '/api/workflows/qualify-lead'
      preLoaderRoute: typeof ApiWorkflowsQualifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/draft-reply': {
      id: '/api/workflows/draft-reply'
      path: '/api/workflows/draft-reply'
      fullPath: '/api/workflows/draft-reply'
      preLoaderRoute: typeof ApiWorkflowsDraftReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/draft-quote': {
      id: '/api/workflows/draft-quote'
      path: '/api/workflows/draft-quote'
      fullPath: '/api/workflows/draft-quote'
      preLoaderRoute: typeof ApiWorkflowsDraftQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/context/lead': {
      id: '/api/workflows/context/lead'
      path: '/api/workflows/context/lead'
      fullPath: '/api/workflows/context/lead'
      preLoaderRoute: typeof ApiWorkflowsContextLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsNameRoute: typeof AgentsNameRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsNameRoute: AgentsNameRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface QuotesRouteChildren {
  QuotesIdRoute: typeof QuotesIdRoute
  QuotesNewRoute: typeof QuotesNewRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesIdRoute: QuotesIdRoute,
  QuotesNewRoute: QuotesNewRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  QuotesRoute: QuotesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  ApiWorkflowsDraftQuoteRoute: ApiWorkflowsDraftQuoteRoute,
  ApiWorkflowsDraftReplyRoute: ApiWorkflowsDraftReplyRoute,
  ApiWorkflowsQualifyLeadRoute: ApiWorkflowsQualifyLeadRoute,
  ApiWorkflowsContextLeadRoute: ApiWorkflowsContextLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
